version: '2'
services:
  web:
    container_name: go-starter
    build: .
    restart: always
    ports:
      - "8008:8008"
    volumes:
      - ./conf:/app/conf
    environment:
      GO_SSO_WORKDIR: /app
      service_env: production
      gin_env: production
      GIN_MODE: release
